# Generated by Django 4.2.13 on 2026-05-07 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_role_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='olt_quota',
            field=models.IntegerField(default=0),
        ),
    ]
