# Generated by Django 4.2.13 on 2026-05-01 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("olts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ONTProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "vendor",
                    models.CharField(
                        choices=[
                            ("ZTE", "ZTE"),
                            ("HUAWEI", "Huawei"),
                            ("ALL", "All Vendors"),
                        ],
                        default="ALL",
                        max_length=20,
                    ),
                ),
                ("download_speed", models.IntegerField(default=100)),
                ("upload_speed", models.IntegerField(default=50)),
                (
                    "protocol",
                    models.CharField(
                        choices=[
                            ("dhcp", "DHCP"),
                            ("pppoe", "PPPoE"),
                            ("static", "Static IP"),
                            ("bridge", "Bridge"),
                        ],
                        default="dhcp",
                        max_length=20,
                    ),
                ),
                ("vlan_id", models.IntegerField(blank=True, null=True)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ONT",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ont_id", models.IntegerField(default=1)),
                ("serial_number", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("online", "Online"),
                            ("offline", "Offline"),
                            ("los", "LOS"),
                            ("power_failure", "Power Failure"),
                            ("fiber_cut", "Fiber Cut"),
                            ("degraded", "Degraded"),
                            ("provisioning", "Provisioning"),
                        ],
                        default="offline",
                        max_length=30,
                    ),
                ),
                (
                    "technology",
                    models.CharField(
                        choices=[
                            ("GPON", "GPON"),
                            ("EPON", "EPON"),
                            ("XGS-PON", "XGS-PON"),
                        ],
                        default="GPON",
                        max_length=20,
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[("routing", "Routing"), ("bridging", "Bridging")],
                        default="routing",
                        max_length=20,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("mac_address", models.CharField(blank=True, max_length=17)),
                ("rx_power", models.FloatField(default=0)),
                ("tx_power", models.FloatField(default=0)),
                ("olt_rx_power", models.FloatField(default=0)),
                ("distance", models.FloatField(default=0)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("address", models.CharField(blank=True, max_length=200)),
                ("vlan", models.IntegerField(default=100)),
                ("uptime", models.BigIntegerField(default=0)),
                ("last_online", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "olt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="onts",
                        to="olts.olt",
                    ),
                ),
                (
                    "pon_port",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="onts",
                        to="olts.ponport",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="onts.ontprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["olt", "pon_port", "ont_id"],
            },
        ),
    ]
