# Generated by Django 4.2.13 on 2026-05-01 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AlertRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("signal_low", "Signal Too Low"),
                            ("signal_high", "Signal Too High"),
                            ("ont_offline", "ONT Offline"),
                            ("olt_offline", "OLT Offline"),
                            ("high_traffic", "High Traffic"),
                            ("temperature", "High Temperature"),
                        ],
                        max_length=30,
                    ),
                ),
                ("threshold", models.FloatField(blank=True, null=True)),
                (
                    "operator",
                    models.CharField(
                        choices=[
                            ("lt", "Less than (<)"),
                            ("gt", "Greater than (>)"),
                            ("eq", "Equal to (=)"),
                        ],
                        default="lt",
                        max_length=5,
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                ("notify_email", models.BooleanField(default=True)),
                ("notify_sms", models.BooleanField(default=False)),
                (
                    "email_recipients",
                    models.TextField(
                        blank=True, help_text="Comma-separated email addresses"
                    ),
                ),
                (
                    "sms_recipients",
                    models.TextField(
                        blank=True, help_text="Comma-separated phone numbers"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="AlertNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[("email", "Email"), ("sms", "SMS")], max_length=10
                    ),
                ),
                ("recipient", models.CharField(max_length=200)),
                ("message", models.TextField()),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                ("delivered", models.BooleanField(default=True)),
                (
                    "rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="alerts.alertrule",
                    ),
                ),
            ],
            options={
                "ordering": ["-sent_at"],
            },
        ),
    ]
