# Generated by Django 4.2.13 on 2026-05-01 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("onts", "0001_initial"),
        ("olts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("online", "ONT Online"),
                            ("offline", "ONT Offline"),
                            ("los", "Loss of Signal"),
                            ("power_failure", "Power Failure"),
                            ("fiber_cut", "Fiber Cut"),
                            ("signal_degraded", "Signal Degraded"),
                            ("olt_online", "OLT Online"),
                            ("olt_offline", "OLT Offline"),
                            ("provisioned", "ONT Provisioned"),
                            ("rebooted", "ONT Rebooted"),
                            ("factory_reset", "Factory Reset"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "Info"),
                            ("warning", "Warning"),
                            ("critical", "Critical"),
                        ],
                        default="info",
                        max_length=20,
                    ),
                ),
                ("message", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("acknowledged", models.BooleanField(default=False)),
                (
                    "olt",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="olts.olt",
                    ),
                ),
                (
                    "ont",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="onts.ont",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="TrafficHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField()),
                ("download_mbps", models.FloatField()),
                ("upload_mbps", models.FloatField()),
                (
                    "ont",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="traffic_history",
                        to="onts.ont",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["ont", "-timestamp"],
                        name="monitoring__ont_id_d13bc5_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SignalHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField()),
                ("rx_power", models.FloatField()),
                ("tx_power", models.FloatField()),
                ("olt_rx_power", models.FloatField()),
                (
                    "ont",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="signal_history",
                        to="onts.ont",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["ont", "-timestamp"],
                        name="monitoring__ont_id_a47ab0_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="OLTMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField()),
                ("cpu_usage", models.FloatField()),
                ("memory_usage", models.FloatField()),
                ("temperature", models.FloatField()),
                (
                    "olt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metrics",
                        to="olts.olt",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["olt", "-timestamp"],
                        name="monitoring__olt_id_4b549f_idx",
                    )
                ],
            },
        ),
    ]
