# Generated by Django 4.2.13 on 2026-05-01 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OLT",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "vendor",
                    models.CharField(
                        choices=[("ZTE", "ZTE"), ("HUAWEI", "Huawei")], max_length=20
                    ),
                ),
                ("model", models.CharField(max_length=50)),
                ("ip_address", models.GenericIPAddressField()),
                ("telnet_port", models.IntegerField(default=23)),
                ("ssh_port", models.IntegerField(default=22)),
                ("username", models.CharField(default="admin", max_length=50)),
                ("password", models.CharField(default="admin", max_length=100)),
                ("location", models.CharField(blank=True, max_length=200)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("online", "Online"),
                            ("offline", "Offline"),
                            ("warning", "Warning"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("snmp_community", models.CharField(default="public", max_length=50)),
                ("firmware_version", models.CharField(blank=True, max_length=50)),
                ("uptime", models.BigIntegerField(default=0)),
                ("cpu_usage", models.FloatField(default=0)),
                ("memory_usage", models.FloatField(default=0)),
                ("temperature", models.FloatField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "OLT",
                "verbose_name_plural": "OLTs",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PONPort",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("board", models.IntegerField(default=1)),
                ("port", models.IntegerField()),
                (
                    "technology",
                    models.CharField(
                        choices=[
                            ("GPON", "GPON"),
                            ("EPON", "EPON"),
                            ("XGS-PON", "XGS-PON"),
                            ("10G-EPON", "10G-EPON"),
                        ],
                        default="GPON",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("up", "Up"),
                            ("down", "Down"),
                            ("degraded", "Degraded"),
                        ],
                        default="up",
                        max_length=20,
                    ),
                ),
                ("max_onts", models.IntegerField(default=128)),
                ("description", models.CharField(blank=True, max_length=200)),
                (
                    "olt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pon_ports",
                        to="olts.olt",
                    ),
                ),
            ],
            options={
                "ordering": ["olt", "board", "port"],
                "unique_together": {("olt", "board", "port")},
            },
        ),
    ]
