# Generated by Django 4.2.13 on 2026-05-06 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('olts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscoveredONT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=50)),
                ('vendor_info', models.CharField(blank=True, max_length=100)),
                ('discovered_at', models.DateTimeField(auto_now=True)),
                ('olt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discovered_onts', to='olts.olt')),
                ('pon_port', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discovered_onts', to='olts.ponport')),
            ],
            options={
                'ordering': ['pon_port', 'serial_number'],
                'unique_together': {('pon_port', 'serial_number')},
            },
        ),
    ]
