# Generated by Django 4.2.13 on 2026-05-07 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olts', '0002_discovered_ont'),
    ]

    operations = [
        migrations.AddField(
            model_name='olt',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='olt',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
