# Generated by Django 4.2.13 on 2026-05-07 07:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('olts', '0003_soft_delete_olt'),
    ]

    operations = [
        migrations.AddField(
            model_name='olt',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='olts', to=settings.AUTH_USER_MODEL),
        ),
    ]
