# Generated by Django 4.2.13 on 2026-05-08 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olts', '0004_add_olt_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='olt',
            name='iptv_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='olt',
            name='pon_type',
            field=models.CharField(choices=[('GPON', 'GPON'), ('EPON', 'EPON'), ('GPON+EPON', 'GPON+EPON')], default='GPON', max_length=20),
        ),
        migrations.AddField(
            model_name='olt',
            name='snmp_port',
            field=models.IntegerField(default=161),
        ),
        migrations.AddField(
            model_name='olt',
            name='snmp_write_community',
            field=models.CharField(default='private', max_length=50),
        ),
    ]
