# Generated by Django 4.2.13 on 2026-05-08 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('olts', '0005_add_snmp_iptv_pon_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='olt',
            name='iptv_enabled',
        ),
    ]
